In [17]:
import pandas as pd
import numpy as np
import h5py
import os

In [12]:
root = "."
df = pd.read_csv(os.path.join(root, "..", "processed", "enamine_REAL_characterization", "enamine_REAL.tsv"), sep='\t')
df['index'] = df.index

In [31]:
smiles = df['smiles'].tolist()[:1000000]

In [32]:
with open("/home/acomajuncosa/Documents/playground/fp2sim/smiles.smi", "w") as f:
    f.write("\n".join([i.split()[0] + " " + str(c) for c, i in enumerate(smiles)]))

In [28]:
from FPSim2.io import create_db_file

mols = [[i, c] for c,i in enumerate(smiles)]
create_db_file(
    mols_source=mols,
    filename='/home/acomajuncosa/Documents/playground/fp2sim/fp_db.h5',
    mol_format='smiles', # required
    fp_type='Morgan',
    fp_params={'radius': 2, 'fpSize': 2048}
)

In [42]:
with h5py.File("/home/acomajuncosa/Documents/playground/fp2sim/fp_db.h5", "r") as f:
    print(f['_i_fps'])
    config = f['config'][:]
    # fps = f['fps'][:]
    # a = np.array(f['fps'])
    # print(a)
    a = f[sorted(f)[2]][:]
    print(sorted(f))
    print(f[sorted(f)[2]])

<HDF5 group "/_i_fps" (1 members)>


OSError: Can't synchronously read data (can't open directory (/usr/local/hdf5/lib/plugin). Please verify its existence)

In [41]:
config

array([array([128,   5, 149,  10,   0,   0,   0,   0,   0,   0,   0, 140,   6,
               77, 111, 114, 103,  97, 110, 148,  46], dtype=uint8)           ,
       array([128,   5, 149,  28,   0,   0,   0,   0,   0,   0,   0, 125, 148,
               40, 140,   6, 114,  97, 100, 105, 117, 115, 148,  75,   2, 140,
                6, 102, 112,  83, 105, 122, 101, 148,  77,   0,   8, 117,  46],
             dtype=uint8)                                                      ,
       array([128,   5, 149,  13,   0,   0,   0,   0,   0,   0,   0, 140,   9,
               50,  48,  50,  52,  46,  48,  57,  46,  54, 148,  46], dtype=uint8),
       array([128,   5, 149,   9,   0,   0,   0,   0,   0,   0,   0, 140,   5,
               48,  46,  55,  46,  51, 148,  46], dtype=uint8)                ,
       array([128,   5, 149, ..., 148, 101,  46], shape=(2830,), dtype=uint8)],
      dtype=object)

In [38]:
a

<Closed HDF5 dataset>